### ISSUE TITLE
JQlite domReady call twice

### ISSUE THREAD

**Issue by csperlich** [power-cosmic/fog#21]
JQlite doesn't seem to be able to handle two calls to the domReady function for a single page.

i.e. if one file says:

``` javascript
$(function() {
 //set stuff up
});
```

and another one says:

``` javascript
$(function() {
 //set stuff up
});
```

then I think the first one get's clobbered, or some other kind of conflict is occurring.

**Comment by tyler-hoffman** [comment]
My fork addresses the issue. I made a PR, but I didn't accept it yet.
jQuery allows for that?

**Comment by tyler-hoffman** [comment]
I accepted it like a million years ago. Just cleaning up here.
